const {JSDOM} = require('jsdom');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const dom = new JSDOM('<div id="poly-list-container"></div><div id="kalshi-market-container"></div>', {runScripts:'outside-only'});
const w = dom.window;
w.fetch=()=>Promise.reject(new Error('No network in tests'));
w.eval(fs.readFileSync('kalshi-markets.js', 'utf8'));
const base = {status:'available',fetched_at:new Date().toISOString(), markets:[]};
w.renderKalshiMarkets(base);
assert.match(w.document.body.textContent,/沒有符合/);
const m = {question:'<img src=x onerror=alert(1)>',question_zh:'合成測試', display_midpoint:0, yes_bid:0,yes_ask:0,volume_contracts:0,quote_status:'two_sided',end_date:'2099-01-01T00:00:00Z'};
w.renderKalshiMarkets({...base,markets:[m]});
assert.match(w.document.body.textContent,/YES 0.0%/);
assert.equal(w.document.querySelector('img'),null);
w.renderKalshiMarkets({...base,status:'stale',markets:[m]});
assert.doesNotMatch(w.document.body.textContent,/YES 0.0%/);
w.WarhubI18n={language:'en'};
w.document.dispatchEvent(new w.Event('warhub-language-change'));
assert.match(w.document.body.textContent,/Current quote unavailable/);
w.renderKalshiMarkets({...base,markets:[{...m,display_midpoint:null}]});
assert.doesNotMatch(w.document.body.textContent,/YES 0.0%/);
console.log('Kalshi UI: empty, zero, stale, missing, English and HTML injection checks passed');
(async()=>{
 const d=new JSDOM('<div id="poly-list-container"></div><div id="kalshi-market-container"></div><div data-kalshi-region="mideast"></div>',{runScripts:'outside-only'});
 let release;
 d.window.fetch=()=>new Promise(resolve=>{release=resolve});
 d.window.eval(fs.readFileSync('kalshi-markets.js','utf8'));
 d.window.renderKalshiMarkets(null);
 d.window.renderKalshiMarkets({...base,markets:[{...m,region:'mideast'}]});
 release({ok:true,json:async()=>({snapshot_kind:'initial_probe',...base,markets:[]})});
 await new Promise(resolve=>setImmediate(resolve));
 assert.equal(d.window.document.querySelectorAll('article').length,1,'late initial data cannot replace scheduled data');
 const ref=d.window.document.querySelector('[data-kalshi-region]');
 assert.match(ref.textContent,/Kalshi/);
 ref.replaceChildren();d.window.refreshKalshiReferences();assert.match(ref.textContent,/Kalshi/);
 d.window.renderKalshiMarkets({...base,markets:[]});assert.equal(ref.textContent,'');
 d.window.close();console.log('Kalshi initial snapshot race and regional redraw checks passed');
})().catch(e=>{console.error(e);process.exitCode=1});
